run:
  deadline: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sawdustofmind/currency-arbitrage
  gocyclo:
    min-complexity: 16
  misspell:
    locale: US
    ignore-words:
      - exmo
  lll:
    line-length: 120
  unused:
    check-exported: false
  unparam:
    check-exported: false

linters:
  fast: false
  enable:
    - gofmt
    - goimports
    - lll
    - unparam
    - misspell

  # defaults
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
  
# Config example:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
